
parameters:
    database_host: localhost
    database_port: null
    database_name: beautetest
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 6855a4dd393a8ac699b4ab2d41844d92027e6d20