<?php

namespace Proxies\__CG__\MyAppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Avis extends \MyAppBundle\Entity\Avis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'id', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'idBT', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'date', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'gender', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'critere', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'presentation', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'texture', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'penetration', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'efficaciteCourtTerme', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'efficaciteLongTerme', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'odeur', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'qualitePrix', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'pointsForts', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'pointsFaibles', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'comments', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'product');
        }

        return array('__isInitialized__', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'id', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'idBT', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'date', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'gender', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'critere', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'presentation', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'texture', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'penetration', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'efficaciteCourtTerme', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'efficaciteLongTerme', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'odeur', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'qualitePrix', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'pointsForts', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'pointsFaibles', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'comments', '' . "\0" . 'MyAppBundle\\Entity\\Avis' . "\0" . 'product');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Avis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBT($idBT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBT', array($idBT));

        return parent::setIdBT($idBT);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBT', array());

        return parent::getIdBT();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritere($critere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritere', array($critere));

        return parent::setCritere($critere);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritere', array());

        return parent::getCritere();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentation($presentation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentation', array($presentation));

        return parent::setPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentation', array());

        return parent::getPresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexture($texture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexture', array($texture));

        return parent::setTexture($texture);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexture', array());

        return parent::getTexture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPenetration($penetration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPenetration', array($penetration));

        return parent::setPenetration($penetration);
    }

    /**
     * {@inheritDoc}
     */
    public function getPenetration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPenetration', array());

        return parent::getPenetration();
    }

    /**
     * {@inheritDoc}
     */
    public function setEfficaciteCourtTerme($efficaciteCourtTerme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEfficaciteCourtTerme', array($efficaciteCourtTerme));

        return parent::setEfficaciteCourtTerme($efficaciteCourtTerme);
    }

    /**
     * {@inheritDoc}
     */
    public function getEfficaciteCourtTerme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEfficaciteCourtTerme', array());

        return parent::getEfficaciteCourtTerme();
    }

    /**
     * {@inheritDoc}
     */
    public function setEfficaciteLongTerme($efficaciteLongTerme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEfficaciteLongTerme', array($efficaciteLongTerme));

        return parent::setEfficaciteLongTerme($efficaciteLongTerme);
    }

    /**
     * {@inheritDoc}
     */
    public function getEfficaciteLongTerme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEfficaciteLongTerme', array());

        return parent::getEfficaciteLongTerme();
    }

    /**
     * {@inheritDoc}
     */
    public function setOdeur($odeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOdeur', array($odeur));

        return parent::setOdeur($odeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getOdeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOdeur', array());

        return parent::getOdeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualitePrix($qualitePrix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualitePrix', array($qualitePrix));

        return parent::setQualitePrix($qualitePrix);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualitePrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualitePrix', array());

        return parent::getQualitePrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsForts($pointsForts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsForts', array($pointsForts));

        return parent::setPointsForts($pointsForts);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsForts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsForts', array());

        return parent::getPointsForts();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsFaibles($pointsFaibles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsFaibles', array($pointsFaibles));

        return parent::setPointsFaibles($pointsFaibles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsFaibles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsFaibles', array());

        return parent::getPointsFaibles();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', array($comments));

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', array());

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\MyAppBundle\Entity\Products $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

}
