<?php

namespace MyAppBundle\Entity;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
     public function findProductsByParametres($data)

    {

        $query = $this->createQueryBuilder('p');
        
        $query->addSelect('COUNT(a.id) as nbavis');
        $query->leftJoin('p.avis','a')       
              ->groupBy('p.id')
              ->orderBy("nbavis", 'DESC');
        $query ->leftJoin('p.category','c');
        
        if($data['sub_categorie'] != '')
        { 
            $query->andWhere('p.category = :categorie')

                   ->setParameter('categorie', $data['sub_categorie']);

        }
        elseif($data['categorie'] != '')
        {
            $query->andWhere('c.parentId = :categorie')

                ->setParameter('categorie', $data['categorie']);
             
            $query->orWhere('p.category = :categorie')

                ->setParameter('categorie', $data['categorie']);
        }
         if($data['product_name'] != '')
        {
                    $query->andWhere('p.name Like :name_search')

                ->setParameter('name_search', "%".$data['product_name']."%");

        } 
        if($data['efficacite_court_terme'] != '')
        {
                    $query->andWhere('a.efficaciteCourtTerme = :eff_c_t')
                          ->setParameter('eff_c_t', $data['efficacite_court_terme']);
        }
        if($data['efficacite_long_terme'] != '')
        {
                    $query->andWhere('a.efficaciteLongTerme = :eff_l_t')
                          ->setParameter('eff_l_t', $data['efficacite_long_terme']);
        }
        if($data['odeur'] != '')
        {
                    $query->andWhere('a.odeur = :odeur')
                          ->setParameter('odeur', $data['odeur']);
        }
        if($data['penetration'] != '')
        {
                    $query->andWhere('a.penetration = :penetration')
                          ->setParameter('penetration', $data['penetration']);
        }
        
        if($data['points_faibles'] != '')
        {
                    $query->andWhere('a.pointsFaibles = :points_faibles')
                          ->setParameter('points_faibles', $data['points_faibles']);
        }
        if($data['points_forts'] != '')
        {
                    $query->andWhere('a.pointsForts = :points_forts')
                          ->setParameter('points_forts', $data['points_forts']);
        }
        if($data['presentation'] != '')
        {
                    $query->andWhere('a.presentation = :presentation')
                          ->setParameter('presentation', $data['presentation']);
        }
        if($data['qualite_prix'] != '')
        {
                    $query->andWhere('a.qualitePrix = :qualite_prix')
                          ->setParameter('qualite_prix', $data['qualite_prix']);
        }
        if($data['texture'] != '')
        {
                    $query->andWhere('a.texture = :texture')
                          ->setParameter('texture', $data['texture']);
        }
        if($data['marque'] != '')
        {
                    $query->andWhere('p.marque = :marque')
                          ->setParameter('marque', $data['marque']);
        }
        return $query->getQuery()->getResult();

    }
}
