<?php

namespace MyAppBundle\Entity;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
     public function findProductsByParametres($data)

    {

        $query = $this->createQueryBuilder('p');
        
        $query->addSelect('COUNT(a.id) as nbavis');
        $query->leftJoin('p.avis','a')       
              ->groupBy('p.id')
              ->orderBy("nbavis", 'DESC');
        $query ->leftJoin('p.category','c');
        
        if($data['sub_categorie'] != '')
        { 
            $query->andWhere('p.category = :categorie')

                   ->setParameter('categorie', $data['sub_categorie']);

        }
        elseif($data['categorie'] != '')
        {
            $query->andWhere('c.parentId = :categorie')

                ->setParameter('categorie', $data['categorie']);
             
            $query->orWhere('p.category = :categorie')

                ->setParameter('categorie', $data['categorie']);
        }
         if($data['product_name'] != '')
        {
                    $query->andWhere('p.name Like :name_search')

                ->setParameter('name_search', "%".$data['product_name']."%");

        }  
        $query->setFirstResult( 0 )
               ->setMaxResults( 2 );
        return $query->getQuery()->getResult();

    }
}
