my_app_homepage:
    path:     /
    defaults: { _controller: MyAppBundle:Default:index }
    
my_app_sous_categ:
    path:     /sous_categories
    defaults: { _controller: MyAppBundle:Default:sous_categories } 
    
my_app_recherche:
    path:     /recherche
    defaults: { _controller: MyAppBundle:Default:recherche }  
    
my_app_recherche_nom:
    path:     /recherchenom
    defaults: { _controller: MyAppBundle:Default:recherche_produit_par_nom }  
    
my_app_recherche_avis:
    path:     /rechercheavis
    defaults: { _controller: MyAppBundle:Default:recherche_nb_avis}
    
my_app_affiche_avis_produit:
    path:     /afficheavis/{id}
    defaults: { _controller: MyAppBundle:Default:affiche_avis_produit}     
